### ISSUE TITLE
Breaks mousewheel scrolling in Firefox.

### ISSUE THREAD

**Issue by mufaddalmw** [eustasy/Smooth-Scroll-ALL-the-Things#5]
Hi, have you tried testing in all latest browsers, seems like its not supported in mozilla. 
##

**Comment by lewisgoddard** [comment]
Likely not, this hasn't been touched in well over a year.

**Comment by lewisgoddard** [comment]
Are you sure you waited for everything to finish loading? http://labs.eustasy.org/Smooth-Scroll-ALL-the-Things/ seems to work for me in Firefox 36.0.1 on elementary OS Luna.

**Comment by mufaddalmw** [comment]
Hey, I tried in Windows 8 - Mozilla, its not scrolling there.
